import Weapon from "../models/weapon.js";

const weapons = {
  handgun: {
    type: "Shooting",
    attack: "1D6",
    range: "Medium",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "Blitz",
    cost: 0,
    sponsor: "",
  },
  machineGun: {
    type: "Shooting",
    attack: "2D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "",
    cost: 2,
    sponsor: "",
  },
  heavyMachineGun: {
    type: "Shooting",
    attack: "3D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "",
    cost: 3,
    sponsor: "",
  },
  miniGun: {
    type: "Shooting",
    attack: "4D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "",
    cost: 5,
    sponsor: "",
  },
  "125mmCannon": {
    type: "Shooting",
    attack: "8D6",
    range: "Double",
    ammo: 3,
    slots: 3,
    crewFired: false,
    specialRules: "Blast, +2 hazard if not Tank",
    cost: 6,
    sponsor: "",
  },
  arcLightningProjector: {
    type: "Shooting",
    attack: "6D6",
    range: "Double",
    ammo: 1,
    slots: 2,
    crewFired: false,
    specialRules: "Arc chain in short range",
    cost: 6,
    sponsor: "Mishkin",
  },
  bazooka: {
    type: "Shooting",
    attack: "3D6",
    range: "Double",
    ammo: 3,
    slots: 2,
    crewFired: false,
    specialRules: "Blast",
    cost: 4,
    sponsor: "",
  },
  bFG: {
    type: "Shooting",
    attack: "10D6",
    range: "Double",
    ammo: 1,
    slots: 3,
    crewFired: false,
    specialRules: "Medium straight backwards, gear=1, haazards +3",
    cost: 1,
    sponsor: "",
  },
  combatLaser: {
    type: "Shooting",
    attack: "3D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "Splash",
    cost: 5,
    sponsor: "",
  },
  miniGun: {
    type: "Shooting",
    attack: "4D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "",
    cost: 5,
    sponsor: "",
  },
  deathRay: {
    type: "Shooting",
    attack: "3D6",
    range: "Double",
    ammo: 1,
    slots: 1,
    crewFired: false,
    specialRules: "5+ un-cancelled hits removes target from play",
    cost: 3,
    sponsor: "Mishkin",
  },
  flamethrower: {
    type: "Shooting",
    attack: "6D6",
    range: "Large Burst",
    ammo: 3,
    slots: 2,
    crewFired: false,
    specialRules: "Splash, Fire. Indirect",
    cost: 4,
    sponsor: "",
  },
  grabberArm: {
    type: "Shooting",
    attack: "3D6",
    range: "Short",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "Toss",
    cost: 6,
    sponsor: "",
  },
  gravGun: {
    type: "Shooting",
    attack: "3D6*",
    range: "Double",
    ammo: 1,
    slots: 1,
    crewFired: false,
    specialRules: "Electrical. Gravity Manipulation",
    cost: 2,
    sponsor: "Mishkin",
  },
  harpoon: {
    type: "Shooting",
    attack: "5D6",
    range: "Double",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "Harpoon",
    cost: 2,
    sponsor: "",
  },
  kineticSuperBooster: {
    type: "Shooting",
    attack: "(6D6)",
    range: "Double",
    ammo: 1,
    slots: 2,
    crewFired: false,
    specialRules: "Gear +1 instead of damage",
    cost: 6,
    sponsor: "",
  },
  magneticJammer: {
    type: "Shooting",
    attack: "",
    range: "Double",
    ammo: null,
    slots: 0,
    crewFired: false,
    specialRules: "Target can't use ammo next activation",
    cost: 2,
    sponsor: "",
  },
  mortar: {
    type: "Shooting",
    attack: "4D6",
    range: "Double",
    ammo: 3,
    slots: 1,
    crewFired: false,
    specialRules: "Indirect",
    cost: 4,
    sponsor: "",
  },
  rockets: {
    type: "Shooting",
    attack: "6D6",
    range: "Double",
    ammo: 3,
    slots: 2,
    crewFired: false,
    specialRules: "",
    cost: 5,
    sponsor: "",
  },
  thumper: {
    type: "Shooting",
    attack: "",
    range: "Medium",
    ammo: 1,
    slots: 2,
    crewFired: false,
    specialRules: "Indirect. Targets make gear+2 (max 6) flip check",
    cost: 4,
    sponsor: "",
  },
  wallOfAmplifier: {
    type: "Shooting",
    attack: "",
    range: "Medium",
    ammo: null,
    slots: 3,
    crewFired: false,
    specialRules: "*See rules",
    cost: 4,
    sponsor: "",
  },
  wreckLobber: {
    type: "Shooting",
    attack: "",
    range: "Double/Dropped",
    ammo: 3,
    slots: 4,
    crewFired: false,
    specialRules: "*See rules, Low-loader, Dumper",
    cost: 4,
    sponsor: "",
  },
  wreckingBall: {
    type: "Shooting",
    attack: "*",
    range: "Short",
    ammo: null,
    slots: 3,
    crewFired: false,
    specialRules: "Steel Ball",
    cost: 2,
    sponsor: "",
  },
  blunderbuss: {
    type: "Shooting",
    attack: "2D6",
    range: "Small Burst",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "Splash",
    cost: 2,
    sponsor: "",
  },
  gasGrenades: {
    type: "Shooting",
    attack: "(1D6)",
    range: "Medium",
    ammo: 5,
    slots: 0,
    crewFired: true,
    specialRules: "Blitz, Choking Gas, Indirect",
    cost: 2,
    sponsor: "",
  },
  grenades: {
    type: "Shooting",
    attack: "1D6",
    range: "Medium",
    ammo: 5,
    slots: 1,
    crewFired: true,
    specialRules: "Blast, Indirect, Blitz",
    cost: 1,
    sponsor: "",
  },
  magnum: {
    type: "Shooting",
    attack: "1D6",
    range: "Double",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "Blast",
    cost: 3,
    sponsor: "",
  },
  molotovCocktails: {
    type: "Shooting",
    attack: "1D6",
    range: "Medium",
    ammo: 5,
    slots: 0,
    crewFired: true,
    specialRules: "Fire, Indirect, Blitz",
    cost: 1,
    sponsor: "",
  },
  shotgun: {
    type: "Shooting",
    attack: "3/2/1D6",
    range: "Short/Medium/Long",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "",
    cost: 4,
    sponsor: "",
  },
  steelNets: {
    type: "Shooting",
    attack: "(3D6)",
    range: "Short",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "Blast",
    cost: 2,
    sponsor: "",
  },
  submachineGun: {
    type: "Shooting",
    attack: "3D6",
    range: "Medium",
    ammo: null,
    slots: 0,
    crewFired: true,
    specialRules: "",
    cost: 5,
    sponsor: "",
  },
  caltropDropper: {
    type: "Dropped",
    attack: "2D6",
    range: "Small Burst",
    ammo: 3,
    slots: 1,
    crewFired: false,
    specialRules: "	Treacherous, remains until damage is caused",
    cost: 1,
    sponsor: "",
  },
  glueDropper: {
    type: "Dropped",
    attack: "",
    range: "Large Burst",
    ammo: 1,
    slots: 1,
    crewFired: false,
    specialRules: "Treacherous, gear -2",
    cost: 1,
    sponsor: "",
  },
  mineDropper: {
    type: "Dropped",
    attack: "4D6",
    range: "Small Burst",
    ammo: 3,
    slots: 1,
    crewFired: false,
    specialRules: "Blast",
    cost: 1,
    sponsor: "",
  },
  napalmDropper: {
    type: "Dropped",
    attack: "4D6",
    range: "Small Burst",
    ammo: 3,
    slots: 1,
    crewFired: false,
    specialRules: "Fire",
    cost: 1,
    sponsor: "",
  },
  oilSlickDropper: {
    type: "Dropped",
    attack: "",
    range: "Large Burst",
    ammo: 3,
    slots: 0,
    crewFired: false,
    specialRules: "Treacherous",
    cost: 2,
    sponsor: "",
  },
  rCCarBombs: {
    type: "Dropped",
    attack: "4D6",
    range: "Short",
    ammo: 3,
    slots: 0,
    crewFired: false,
    specialRules: "Remote-Controlled Car",
    cost: 3,
    sponsor: "",
  },
  sentryGun: {
    type: "Dropped",
    attack: "2D6",
    range: "Short/Medium",
    ammo: 3,
    slots: 0,
    crewFired: false,
    specialRules: "Sentry Gun",
    cost: 3,
    sponsor: "",
  },
  smokeDropper: {
    type: "Dropped",
    attack: "",
    range: "Large Burst",
    ammo: 3,
    slots: 0,
    crewFired: false,
    specialRules: "Provides cover",
    cost: 1,
    sponsor: "",
  },
  ram: {
    type: "Smash",
    attack: "+2D6",
    range: "Smash",
    ammo: null,
    slots: 1,
    crewFired: false,
    specialRules: "No hazards gained during collisions on declared facing",
    cost: 4,
    sponsor: "",
  },
  explodingRam: {
    type: "Smash",
    attack: "+6D6",
    range: "Smash",
    ammo: 1,
    slots: 0,
    crewFired: false,
    specialRules: "Highly Explosive. Limit of 1",
    cost: 3,
    sponsor: "",
  },
};

export const createWeapon = async (req, res) => {
  try {
    const weapon = weapons[req.body.weapon];
    weapon.vehicle_id = req.body.id;
    const newWeapon = Weapon.build(weapon);
    await newWeapon.save();
    res.status(201).send(newWeapon);
  } catch (err) {
    console.log("error ==> ", err);
  }
};
